### ISSUE TITLE
Funktioniert das noch bei jemandem?

### ISSUE THREAD

**Issue by wizzardking** [cytec/nzb.to-nZEDb#16]
Hallo zusammen
Läuft der Proxy bei euch noch?

**Comment by anonvoy** [comment]
Ja, läuft hier.

**Comment by nilleiz** [comment]
Ich habe seit kurzem probleme mit Radarr und Sonarr:
"Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

Mein Tor Proxy sagt, dass die Adresse die aufgerufen wird nicht V3 ist, und das nicht unterstützt wird.  
Hängt das vielleicht damit zusammen?
Jemand sonst einen Tipp?

Grüße

//EDIT:

Ich habe das ganze wieder zum Laufen gebracht, indem ich die aktuelle .onion-Adresse in der nzbto.php eingetragen habe, und zu einem anderen Tor-Proxy gewechselt bin. Auch hier muss man entsprechende Adresse und Port des Proxys in der config.inc.php aktualisieren.
Anschließend einmal den Cache löschen und es funktioniert wieder wie vorher.

**Comment by bwilberg** [comment]
@nilleiz: Danke für deine Hinweise, ich habe entsprechend die .onion - Adresse angepasst. Ich kann auch die "caps" manuell abfragen. Das sehe ich auch im nzbto-Proxy im Logfile. Dennoch funktioniert die Einbindung in Sonarr nicht, da er keine Kategorien findet. 
Hast du noch eine Idee? Welchen Tor-Proxy nutzt du?

Grüße
Bernd

**Comment by neilli3** [comment]
Moin, ich nutze dieses Docker Image als Proxy:
dperson/torproxy:latest

Hast du den Cache des nzbtoproxy Containers gelöscht?
Im Container: /var/www/cache

Mach das am besten nach jeder Änderung die du an der Konfiguration machst.

**Comment by bwilberg** [comment]
Moin,
den gleichen Container nutze ich auch. Ich hab auch den Cache gelöscht und im Log auf dem nzbtoproxy sehe ich die Anfrage.
Seit heute bekomme ich plötzlich in Sonarr Ergebnisse, allerdings völlig falsche. Wenn ich eine manuelle Suche starte, dann sind in der Liste komplett andere Folgen.
Was mir auch auffällt: Ich bekomme immer nur maximal 50 Resultate vom nzbtoproxy. Wenn ich in Sonarr eine Suche auf eine Folge einer Serie starte, dann sucht er nur nach dem Namen der Serie und nicht z.B. nach S01E02. Damit hab ich teilweise zu wenig Ergebnisse und das relevante Ergebnis fehlt. Kann man das anpassen?

Ich werd nochmal weitersuchen.

Danke für die schnelle Antwort.

**Comment by nilleiz** [comment]
Moin,

das ist normal bei dem "Indexer", dass bei der manuellen Suche viele
falsche Ergebnisse zurückkommen.
Wenn du aber welche siehst, heißt es, dass alles soweit funktioniert.
Die RSS-Suche findet bei mir definitiv richtige Artikel, sowohl in Sonarr
als auch in Radarr.

Grüße!

Am Do., 29. Sept. 2022 um 08:47 Uhr schrieb bwilberg <
***@***.***>:

**Comment by logo000** [comment]
Danke erstmal für den Workaround. Allerdings will es bei mir ums verrecken nicht funktionieren. Bei mir kommt bei NzbHydra2 sowie auch bei Sonarr direkt nur "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings."
Kann einer der den Fix eingespielt hat vll. mal einen Fork erstellen?

Grüße


//EDIT: Habe es jetzt hinbekommen und direkt in einem Fork übertragen. Größten Dank an [nilleiz](https://github.com/nilleiz) für seinen Workaround. Link zum Fork https://github.com/logo000/nzb.to-nZEDb-V3

Beste Grüße

**Comment by FloppyDiskX** [comment]
Hi, bekomme mit dem V3 immer HTTP Error 500. V2 hat funktioniert. Log sieht auch sauber aus.

`torproxy_1    | Jan 01 20:05:45.000 [notice] Bootstrapped 100% (done): Done
nzbtoproxy_1  | *** Run files in /etc/my_runalways/
nzbtoproxy_1  | *** Running /etc/rc.local...
nzbtoproxy_1  | *** Booting supervisor daemon...
nzbtoproxy_1  | *** Supervisor started as PID 21
nzbtoproxy_1  | 2023-01-01 20:05:48,783 CRIT Set uid to user 0
nzbtoproxy_1  | *** Started processes via Supervisor......
nzbtoproxy_1  | apache2                          RUNNING    pid 26, uptime 0:00:04
nzbtoproxy_1  | crond                            RUNNING    pid 25, uptime 0:00:04
nzbtoproxy_1  | syslog-ng                        RUNNING    pid 24, uptime 0:00:04
nzbtoproxy_1  |
torproxy_1    | Jan 01 20:13:35.000 [warn] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)
torproxy_1    | Jan 01 20:13:35.000 [warn] Socks version 71 not recognized. (This port is not an HTTP proxy; did you want to use HTTPTunnelPort?)

`

**Comment by nilleiz** [comment]
> Danke erstmal für den Workaround. Allerdings will es bei mir ums verrecken nicht funktionieren. Bei mir kommt bei NzbHydra2 sowie auch bei Sonarr direkt nur "Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings." Kann einer der den Fix eingespielt hat vll. mal einen Fork erstellen?
> 
> Grüße
> 
> //EDIT: Habe es jetzt hinbekommen und direkt in einem Fork übertragen. Größten Dank an [nilleiz](https://github.com/nilleiz) für seinen Workaround. Link zum Fork https://github.com/logo000/nzb.to-nZEDb-V3
> 
> Beste Grüße

Jetzt hats bei mir den Geist aufgegeben.
LIegts an mir oder hat sich wieder was geändert?

**Comment by logo000** [comment]
> 

Bei mir funktioniert es noch. Ich habe bei meinem Fork allerdings auch den ursprünglichen Webserver den Cytec gewählt hatte drin gelassen. Vll. Kommt es deswegen bei dir zu Komplikationen?. 

Was bei mir nie funktioniert hatte, den Indexer in nzbhydra zu implementieren. Prowlarr funktioniert soweit. Nutze diesen indexer hier aber auch nur als Backup fürs Backup. Weil Ergebnisse und Verfügbarkeit teilweise mau sind. 

Grüße

**Comment by nilleiz** [comment]
Ich habe mir deinen Fork noch einmal auf einer frischen Umgebung neu aufgesetzt.
Leider das gleiche Spiel.
ich befürchte, jemand hat keinen Account gehijacked.
Bekomme nur noch diese Meldung:
"Query successful, but no results in the configured categories were returned from your indexer. This may be an issue with the indexer or your indexer category settings."

**Comment by nilleiz** [comment]
Habs auch wieder zum Laufen gebracht.
Ich hatte das Problem, dass ich mehrfach das Passwort falsch eingegeben habe in der Anmeldemaske des Portals, deswegen wurde ein Captcha abgefragt, was eben über den Proxy nicht lösbar war.
Da ich mein Passwort nicht mehr wusste, habe ich ein Script geschrieben, welches mir den "API-Key" der über dieses Projekt erstellt wird, wieder entschlüsselt. Man erhält also Benutzernamen und Passwort zurück, sofern man seinen SALT-Key noch hat.
Falls jemand Interesse hat, gerne melden.

Grüße

**Comment by Anakim** [comment]
> Habs auch wieder zum Laufen gebracht. Ich hatte das Problem, dass ich mehrfach das Passwort falsch eingegeben habe in der Anmeldemaske des Portals, deswegen wurde ein Captcha abgefragt, was eben über den Proxy nicht lösbar war. Da ich mein Passwort nicht mehr wusste, habe ich ein Script geschrieben, welches mir den "API-Key" der über dieses Projekt erstellt wird, wieder entschlüsselt. Man erhält also Benutzernamen und Passwort zurück, sofern man seinen SALT-Key noch hat. Falls jemand Interesse hat, gerne melden.
> 
> Grüße

Moin
also mich würde das mal interessieren
Danke

**Comment by nilleiz** [comment]
@Anakim 
Dieses php-Script in `/var/www/httpdocs/inc ` ablegen, und im Container oder im OS via `php ./decrypt_nzbto_api.php` ausführen. 
Dir bekannten Salt-Key und API-Key einfügen und fertig. 
.txt Endung entfernen nicht vergessen.

[decrypt_nzbto_api.php.txt](https://github.com/cytec/nzb.to-nZEDb/files/15326399/decrypt_nzbto_api.php.txt)

**Comment by Anakim** [comment]
Danke
hab das mal ausprobiert. Abfrage SALT_KEY und API passt so weit aber die Rückmeldung ist nur Kauderwelsch .. hab die API noch mal geändert ohne Ergebnis.

Mach ich was falsch?
Mein Proxy funktioniert übrigens wohl seit einer Weile nicht mehr. Will nicht ausschließen dass das Problem auch hier liegt..

Ausgabe der Meldung ist so 

`PHP Fatal error:  Uncaught Error: Call to undefined function mcrypt_get_iv_size() in /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php:14
Stack trace:
#0 /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php(37): Security::decryptUsingMcrypt('NGAAB23NfBIj/qM...', 'SALT_KEY...')
#1 {main}
  thrown in /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php on line 14

Fatal error: Uncaught Error: Call to undefined function mcrypt_get_iv_size() in /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php:14
Stack trace:
#0 /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php(37): Security::decryptUsingMcrypt('NGAAB23NfBIj/qM...', 'SALT_KEY...')
#1 {main}
  thrown in /volume1/docker/nzb.to-nZEDb/httpdocs/inc/decrypt_nzbto_api.php on line 14`

den SALT_KEY hab ich ersetzt 😉
